export const PROPERTIES = [
  {
    id: '1',
    title: '3 BHK Apartment in Koramangala',
    location: 'Koramangala, Bengaluru',
    area: 'Koramangala',
    city: 'Bengaluru',
    price: 35000,
    deposit: 210000,
    bhk: '3 BHK',
    sqft: 1450,
    beds: 3,
    baths: 2,
    type: 'Full House',
    furnished: 'Semi-furnished',
    parking: true,
    petFriendly: false,
    gym: true,
    lift: true,
    security: true,
    postedBy: 'Owner',
    ownerName: 'Suresh Kumar',
    ownerPhone: '+91 98765 43210',
    rating: 4.3,
    reviews: 12,
    colorStart: '#E8121A',
    colorEnd: '#FF6F00',
    tag: 'Zero Brokerage',
    available: 'Immediate',
  },
  {
    id: '2',
    title: '2 BHK Flat in Indiranagar',
    location: 'Indiranagar, Bengaluru',
    area: 'Indiranagar',
    city: 'Bengaluru',
    price: 28000,
    deposit: 168000,
    bhk: '2 BHK',
    sqft: 1100,
    beds: 2,
    baths: 2,
    type: 'Full House',
    furnished: 'Furnished',
    parking: true,
    petFriendly: true,
    gym: false,
    lift: true,
    security: true,
    postedBy: 'Owner',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 87654 32109',
    rating: 4.6,
    reviews: 28,
    colorStart: '#1565C0',
    colorEnd: '#00897B',
    tag: 'Pet Friendly',
    available: 'Immediate',
  },
  {
    id: '3',
    title: '1 BHK in HSR Layout',
    location: 'HSR Layout, Bengaluru',
    area: 'HSR Layout',
    city: 'Bengaluru',
    price: 16000,
    deposit: 96000,
    bhk: '1 BHK',
    sqft: 620,
    beds: 1,
    baths: 1,
    type: 'Full House',
    furnished: 'Unfurnished',
    parking: false,
    petFriendly: false,
    gym: false,
    lift: false,
    security: true,
    postedBy: 'Owner',
    ownerName: 'Ramesh Nair',
    ownerPhone: '+91 76543 21098',
    rating: 4.0,
    reviews: 8,
    colorStart: '#6A1B9A',
    colorEnd: '#E8121A',
    tag: 'New Listing',
    available: '15 Days',
  },
  {
    id: '4',
    title: 'PG for Boys in Whitefield',
    location: 'Whitefield, Bengaluru',
    area: 'Whitefield',
    city: 'Bengaluru',
    price: 8000,
    deposit: 16000,
    bhk: 'PG',
    sqft: 200,
    beds: 1,
    baths: 1,
    type: 'PG/Hostel',
    furnished: 'Furnished',
    parking: false,
    petFriendly: false,
    gym: false,
    lift: false,
    security: true,
    postedBy: 'Owner',
    ownerName: 'Kavitha Reddy',
    ownerPhone: '+91 65432 10987',
    rating: 3.8,
    reviews: 45,
    colorStart: '#2E7D32',
    colorEnd: '#1565C0',
    tag: 'Meals Included',
    available: 'Immediate',
  },
  {
    id: '5',
    title: '4 BHK Villa in JP Nagar',
    location: 'JP Nagar, Bengaluru',
    area: 'JP Nagar',
    city: 'Bengaluru',
    price: 75000,
    deposit: 450000,
    bhk: '4 BHK',
    sqft: 2800,
    beds: 4,
    baths: 3,
    type: 'Full House',
    furnished: 'Furnished',
    parking: true,
    petFriendly: true,
    gym: true,
    lift: false,
    security: true,
    postedBy: 'Owner',
    ownerName: 'Anil Mehta',
    ownerPhone: '+91 54321 09876',
    rating: 4.8,
    reviews: 6,
    colorStart: '#FF6F00',
    colorEnd: '#E8121A',
    tag: 'Premium',
    available: '30 Days',
  },
];

export const SERVICES = [
  { id: 's1', icon: 'cube-outline', label: 'Packers & Movers', color: '#E8121A' },
  { id: 's2', icon: 'school-outline', label: 'Pay Tuition Fee', color: '#1565C0', badge: 'New' },
  { id: 's3', icon: 'document-text-outline', label: 'Rental Agreement', color: '#2E7D32' },
  { id: 's4', icon: 'cash-outline', label: 'Click & Earn', color: '#FF6F00' },
  { id: 's5', icon: 'brush-outline', label: 'Painting & Cleaning', color: '#6A1B9A', badge: 'New' },
  { id: 's6', icon: 'globe-outline', label: 'NoMediator For NRIs', color: '#00897B', badge: 'New' },
];

export const PROPERTY_TYPES = ['Full House', 'PG/Hostel', 'Flatmates'];
export const BHK_TYPES = ['1 RK', '1 BHK', '2 BHK', '3 BHK', '4 BHK', '4+ BHK'];
export const CITIES = ['Bengaluru', 'Mumbai', 'Delhi', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata'];

export const LOCALITIES = [
  'Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield',
  'JP Nagar', 'Marathahalli', 'Electronic City', 'Bellandur',
  'BTM Layout', 'Jayanagar', 'Bannerghatta Road', 'Yelahanka',
];
